### ISSUE TITLE
collection ready not working 

### ISSUE THREAD

**Issue by jinwyp** [loneleeandroo/ngMeteor#10]
I follow the readme, and use ready function.

```
$collection("todos", $rootScope)
$scope.todos.ready(function(){ ... })
```

then got error 
Object [object Array] has no method ready

btw, $collection("todos", $rootScope)  .  The "todos"  is the same word as the meteor collection.  Is there a way to change the another name used in angular controller?   Because meteor collection is a model which use capital word , and in angular scope , I always use lower case of data source.

**Comment by loneleeandroo** [comment]
Hello :)

Yea i only added the ready method today, so you might need to update to the latest ngMeteor using:

```
mrt update
```

If you want to give it an alias you could do:

```
Todos = $collection("todos", $rootScope);
Todos.ready(function(){ ... });
```

**Comment by jinwyp** [comment]
cool!

**Comment by jinwyp** [comment]
I try the newest version, and

```
Todos = $collection("todos", $rootScope);
Todos.ready(function(){ ... }); 
```

not working 

in angular template I can't use ng-repeat = "todo in Todos"

and I have another problem that the new ngMeteor is confilit with meteor accounts-UI,
It got "Cannot read property 'username" of undefined "

**Comment by loneleeandroo** [comment]
Hello :)

You need to remove the autopublish smart package in order for the ready() method to work.

The accounts-ui conflict is happening because the helpers in the accounts-ui templates are run when they are being put into $templateCache. One of those helpers was looking for Meteor.user(), but that was returning null because no users were logged in. So what i've done in ngMeteor v0.1.18, is I've chosen to ignore all templates that have a name starting with "_", so that it won't run the helper functions.

ng-repeat should work. Try this out:

### example.html

```
<head>
  <title>debug</title>
</head>

<body>
  {{loginButtons}}
  {{> hello}}
</body>

<template name="hello">
    <div ng-controller="TodoCtrl">
        <ul>
            <li ng-repeat="todo in todos">[[todo.text]] <button ng-click="deleteTodo(todo)">Delete</button></li>
        </ul>
        <form>
            <input ng-model="newTodo.text">
            <button type="submit" ng-click="addTodo(newTodo)">Submit</button>
        </form>
    </div>
</template>
```

### example.js

```
todos = new Meteor.Collection("todos");

if (Meteor.isClient) {

  ngMeteor.controller("TodoCtrl", ['$scope','$collection', function($scope, $collection){

    Todos = $collection('todos', $scope);

    $scope.addTodo = function(todo){
      Todos.add(todo);
      $scope.newTodo.text = "";
    }

    $scope.deleteTodo = function(todo){
      Todos.delete(todo);
    }

    Todos.ready(function(){
      console.log("Ready");
    })

  }]);
}

if(Meteor.isServer){
  Meteor.publish("todos",function(selector,options,publisher){
    return todos.find({});
  });


}
```

**Comment by jinwyp** [comment]
Sorry , I may got misunderstand of this question.

I want to use another name of collection which can used in template. In above example , I want use 'Todos' in template not 'todos' because I don't want to used the same name of Meteor collection 'todos'.

```
   <li ng-repeat="todo in Todos">
```

Is there a ways to do that ? 

btw in above example , missing "Meteor.subscribe("todos");"  in client part.

**Comment by loneleeandroo** [comment]
Its not missing :) $collection does the Meteor.subscribe automatically, so i don't need to include it.

So you want to use <code>Todos</code> in the template and <code>todos</code> as the collection name?

Sure, this is how you would set it up:

### js

```
Todos = new Meteor.Collection("todos");

if (Meteor.isClient) {
  ngMeteor.controller("TodoCtrl", ['$scope','$collection', function($scope, $collection){
    $collection('Todos', $scope);

    $scope.Todos.ready(function(){
      console.log("Ready");
    })
  }]);
}

if(Meteor.isServer){
  Meteor.publish("Todos",function(selector,options,publisher){
    return Todos.find({});
  });
}
```

### html

```
<div ng-controller="TodoCtrl">
        <ul>
            <li ng-repeat="todo in Todos">[[todo]]</li>
        </ul>
</div>
```
