### ISSUE TITLE
HTML binding does not work

### ISSUE THREAD

**Issue by aralshukaili** [loneleeandroo/ngMeteor#2]
I tried to get ngMeteor (v0.1.7) working. The JS code runs without errors, however the data binding in the HTML code does not work. This is the code:

![screen shot 2014-02-11 at 1 19 22 pm](https://f.cloud.github.com/assets/788928/2133391/29ea73e2-92c3-11e3-9e4a-697e70de7f9e.png)

This is what i get: [[foo]]
However, I should get: bar

Thoughts?

**Comment by aralshukaili** [comment]
After some trial and error... It appears that ngMock is the colporate. In the ngMeteor package folder:

ngMeteor.js
![screen shot 2014-02-11 at 3 29 39 pm](https://f.cloud.github.com/assets/788928/2134059/3b210a06-92d5-11e3-9e66-911fb494c9b1.png)

I think ngMock does not play well with angular.bootstrap function, not sure though. However commenting out ngMock solves the problem.

Please add the fix after confirming the issue :)

Cheers

**Comment by loneleeandroo** [comment]
Okay :O thanks for that, i'll take out ngMock for now.

**Comment by loneleeandroo** [comment]
I'll put it back in once i understand why its not playing well :)

**Comment by aralshukaili** [comment]
No worries. Let me know once you figure it out. Very peculiar bug this one!

**Comment by ccll** [comment]
Another similar issue, `api.add_files(['lib/angular-mocks.js'])` breaks `mrt/meteor --production` instance.
Some injection in angular-mocks.js did not use string form like `['$rootScope', function($rootScope...`, so the injected provider name was obfuscated and then failed to inject.

**Comment by aralshukaili** [comment]
Makes sense. Thank you very much for the info.

**Comment by loneleeandroo** [comment]
Yea i've taken both Angular Mock and Angular Scenario out of the package.

**Comment by ccll** [comment]
Great!
Seems like ngMock was not polished enough.
