### ISSUE TITLE
use 2.0 by now

### ISSUE THREAD

**Issue by crapthings** [loneleeandroo/ngMeteor#22]
i've saw 0.2 on branch and all features seem 100% unless document. can we use it right now? when will u rls 0.2?

**Comment by crapthings** [comment]
really need multiple collections subscribe support right now

**Comment by Urigo** [comment]
Hi @loneleeandroo, any news on that?

**Comment by Urigo** [comment]
@loneleeandroo I'm the owner of a development team and we work a lot with ngMeteor and really happy with your solution.
I'm also a member of the angular-ui team.
Me and my team would love to join in as a collaborators to your library and help you push it forward.
What do you think?
Thanks!

**Comment by leoetlino** [comment]
That would be a great news!

**Comment by Urigo** [comment]
@crapthings @leoetlino 
After trying to update ngMeteor with pull requests for a while, it looks like ngMeteor is not really supported...
So i've forked ngMeteor and added support to Meteor 0.8.3 to the 0.2 branch.
I've also pull requested it but still no response.
So I guess me and my team will support our fork from now on.
Here it is:
https://github.com/Urigo/ngMeteor/tree/v0.2

We would love for you to use our repo and submit issues and pull requests there.
In a week or so we will merge 0.2 branch to master on our repo.

Good luck to us all and I hope that we could merge back here someday....

**Comment by Urigo** [comment]
We've just released a new version of our fork of ngMeteor with a lot of changes that also supports version 2 and the new Meteor's packaging system (since version 0.9.0):
https://github.com/Urigo/ngmeteor/releases
Have fun

**Comment by crapthings** [comment]
this is awesome.
i'll try the new repo.
