### ISSUE TITLE
Some errors with Iron-router

### ISSUE THREAD

**Issue by darkship** [loneleeandroo/ngMeteor#27]
Hi,
I just added ngMeteor to my app that use Meteor's Template and Iron-router.
I've go an error on line 40 of packages/ngMeteor/modules/ngMeteor-template.js each time I render a template. Because "key" is undefined

<pre>
angular.element(document).ready(function() {                                                                           // 34
    if(Package['iron-router']){                                                                                        // 35
        var oldRun = Router.run;                                                                                       // 36
        Router.run = function() {                                                                                      // 37
            var runResult = oldRun.apply(this, arguments);                                                             // 38
            key = this._currentController.template                                                                     // 39
            var oldRendered = Template[key].rendered;                                                                  // 40
            Template[key].rendered = function(){                                                                       // 41
                angular.element(document).injector().invoke(['$compile', '$document', '$rootScope', function($compile, $document, $rootScope){
                    $compile($document)($rootScope);                                                                   // 43
                    $rootScope.$digest();                                                                              // 44
                    oldRendered.apply(this, arguments);                                                                // 45
                }]);                                                                                                   // 46
                Template[key].rendered = oldRendered;                                                                  // 47
            }                                                                                                          // 48
            return runResult;                                                                                          // 49
        };                                                                                                             // 50
    }        
</pre>

It occurs after <code>TypeError: self.template is not a function</code> on line 296 in packages/blaze-layout/layout.js: 

<pre>
var tmplName = self.template();                                                                                 // 296
</pre>

Did I miss something? I do not see anything weird on my page.

I would like that angularJS coexists with my current code since I have some rendering performance issues with Template. I tried ngMeteor with a new project and it was very nice.

Edit:
I reproduced the error. I created a new project, added Iron-Router and ngMeteor and I defined this route:

<pre>
Router.map(function () {
        this.route("home", {
            template:"hello",
            path: '/'
        });
    })
</pre>

**Comment by ghost** [comment]
Hello,

Could you describe what was the problem in your case?
I am trying to use the following package:
https://github.com/cramrov/meteor-ionic/
together with Iron-Router, but still I recieve the same error like you.

https://github.com/tommyJS/tommyJS-repo

If you know what I did wrong, please let me know :)
Thanks.

**Comment by darkship** [comment]
@tommyJS you shouldn't use iron-router on a new project for now. 
ngMeteor detects Iron-router and wants to add some code so that angularJS works but somehow we lost some functions

**Comment by stephenkaraga** [comment]
Is there a workaround or any word on when ngMeteor and Iron router will be compatible?

We ran into this issue working on a new app, there seems to be a compatibility issue.

**Comment by Urigo** [comment]
@darkship @stephenkaraga @tommyJS  We've just released a new version of our fork of ngMeteor with a lot of changes that also supports the new Meteor's packaging system (since version 0.9.0).
If this issue is still relevant for you we would love to support it on our repo:
https://github.com/Urigo/ngmeteor
Thanks
