### ISSUE TITLE
Collection existence check condition 

### ISSUE THREAD

**Issue by aralshukaili** [loneleeandroo/ngMeteor#3]
Regarding this line:

```
var collection = $window[name];
```

in ngMeteor-collections.js:

```
var ngMeteorCollections = angular.module('ngMeteor.collections', []);
ngMeteorCollections.factory('$collection', ['$window', '$rootScope', 'HashKeyCopier',
    function($window, $rootScope, HashKeyCopier){
        return function (name, scope, selector, options) {
            var collection = $window[name];
            if(!selector) selector = {};
            if(collection instanceof Meteor.Collection){
```

In your package, I don't think you store any collection declaration in $window. Furthermore, you don't mention in your documentation to store collection declarations in $window. Hence, using $collection function always go to:

```
} else {
    console.error('There is no Meteor Collection called "' + name + '"')
}
```

Correct me if I missed something.

**Comment by loneleeandroo** [comment]
ngMeteor just uses the default Meteor Collection declaration, which stores their collection in <code>window</code>. So for example:

```
Leaders = new Meteor.Collection("Leaders");
```

would create an Meteor.Collection object in window.

This is an example of [a simple leaderboard](https://github.com/loneleeandroo/ngMeteor/issues/1#issuecomment-34165850)

**Comment by loneleeandroo** [comment]
I'll mention it in the README.
