### ISSUE TITLE
Support reactive-table

### ISSUE THREAD

**Issue by leoetlino** [loneleeandroo/ngMeteor#30]
Currently, ngMeteor doesn't support [reactive-table](https://github.com/ecohealthalliance/reactive-table).

When `{{> reactiveTable collection=Collection}}` is added to a template, ngMeteor will fail with the following error:

```
Error: HTML.Raw must be constructed with a string
    at new HTML.Raw (http://localhost:3000/packages/htmljs.js:11)
    at http://localhost:3000/packages/ngMeteor.js:27935:35
```

htmljs.js:11 checks that it's being passed a string. If something else is passed to HTML.Raw(), it will throw the above error.

ngMeteor-template.js passes in `$templateCache.get(transcludeTemplateName)` (with transcludeTemplateName = 'Component'). However, the template cache obviously does not have the markup for 'Component' and returns undefined, resulting in the above error.

Fortunately, `Component` has a `render()` method that returns the HTML markup. So maybe we could check if `v` is a Component and calls render() as appropriate?

```
// example code
templateRender[k] = (transcludeTemplateName === 'Component')
    ? v.render()
    : new HTML.Raw($templateCache.get(transcludeTemplateName));
```

Maybe there's a better solution for this.

**Comment by leoetlino** [comment]
Well, even with the workaround, it still won't work.

The options aren't passed at all, apparently. If someone has any idea...

**Comment by Urigo** [comment]
@leoetlino I was dealling with something similar trying to include the accounts templates as is inside an ngMeteor template.
If you still looking for support you can reopen the issue on our repo and we can discuss it there:
https://github.com/Urigo/ngmeteor
Thanks
