### ISSUE TITLE
ngMeteor breaks with Meteor 0.8.3

### ISSUE THREAD

**Issue by leoetlino** [loneleeandroo/ngMeteor#31]
Meteor 0.8.3 seems to have changed Template.templateName.render() to Template.templateName.__render(), so the current ngMeteor breaks under 0.8.3.

**Comment by thosmos** [comment]
This fixed it for me: https://github.com/loneleeandroo/ngMeteor/pull/32

**Comment by leoetlino** [comment]
Indeed! Although I do have a small concern, though. See the pull request for more details.

**Comment by leoetlino** [comment]
Closing, as the pull request has been merged.
