### ISSUE TITLE
$collection - Support promises

### ISSUE THREAD

**Issue by leoetlino** [loneleeandroo/ngMeteor#33]
Currently, $collection seems to be getting the data asynchronously. This results in race conditions if the collection takes some time before it is completely loaded.

Would it be possible to add support for promises, or something else that would allow to avoid race conditions?

**Comment by Urigo** [comment]
@leoetlino still relevant in the new release on our repo?
https://github.com/Urigo/ngmeteor/releases

**Comment by leoetlino** [comment]
I've solved it by having a `setTimeout()` that periodically checks if collections are ready and if they're not, wait and try again until it's ready.

However, I think it would be much cleaner if we could just delay loading the route until the collections are ready. Maybe allowing collections to be injected will solve the problem?

**Comment by Urigo** [comment]
Can you show an example?
maybe on http://meteorpad.com/?

**Comment by leoetlino** [comment]
Here's how I do it in a controller:

```
var getJobDetails = function () {
    if (!areCollectionsReady()) {
        setTimeout(getJobDetails, 1000);
        return;
    }

    $collection(androidAppsBuildJobs, $routeParams.id).bind($scope, 'buildJobs');

    if (!$scope.buildJobs.length) {
        // The job doesn't exist. Aborting.
        $location.path('/build-jobs');
        return;
    }

    $scope.job = $scope.buildJobs[0];
};

getJobDetails();

// Keep $scope.app and $scope.apps[0] synchronised
// since ngMeteor hasn't got a method for that
$scope.$watch('buildJobs', function (newValue, oldValue) {
    if (angular.equals(newValue, oldValue)) {
        return;
    }
    $scope.job = $scope.buildJobs[0];
});
```

Where `areCollectionsReady()` is just:

```
if (Meteor.isClient) {
    var subscriptions = [];

    subscriptions.push({ name: 'androidAppsBuildJobs', handle: Meteor.subscribe('androidAppsBuildJobs') });

    this.subscriptions = subscriptions;
    this.areCollectionsReady = function () {
        var isReady = subscriptions.every(function (subscription) {
            return subscription.handle.ready();
        });
        return isReady;
    };
}
```

**Comment by Urigo** [comment]
@leoetlino Haven't forgot!  will be on this in less than a week.
In the meantime if you have a suggestion for a solution you can start a pull request, even if it's not fully completed we can work on it together.

**Comment by leoetlino** [comment]
I think the way to do it would be a `resolve` property on the route that directly injects the collection to the controller and delays loading appropriately. I don't have the skills to add it though!

**Comment by Urigo** [comment]
@leoetlino I've went through your example again and I have a few questions.
It looks like you are waiting for the androidAppsBuildJobs collection to be ready.
Where are you subscribing to it?

Maybe there you can use the onready callback, something like:
      Meteor.subscribe('androidAppsBuildJobs', function(){
        getJobDetails();
      });

I'm not try to remove the problem but to find the best solution so if it doesn't seem optimal please tell me..

Hope you are enjoying the versions of ngmeteor :)
https://github.com/Urigo/ngmeteor/releases

**Comment by leoetlino** [comment]
The model is defined in `models.js` in my project, and the subscribe call is in that file also.

What I hoped is that ngMeteor would have a native way to inject collections into a controller and delaying the loading of the route until the collection is ready, just like regular `resolve` properties on a route.

As you can see, I'm already manually checking that the collections are ready before doing anything that requires them, so that's not a big issue.

**Comment by Urigo** [comment]
@leoetlino I've added support for subscribing automatically with the bind function and also separately with a new $subscribe service.
Here is the commit:
https://github.com/Urigo/ngmeteor/commit/3436e7534fda4ef71042267d36a17fd41533bfe4

I've also updated the tutorial:
http://angularjs.meteor.com/tutorial/step_00

And also updated the docs here:
https://github.com/Urigo/ngmeteor

Please share your thoughts
