### ISSUE TITLE
loading jquery before angular

### ISSUE THREAD

**Issue by netanelgilad** [loneleeandroo/ngMeteor#35]
Hi,
I got an issue with using jquery instead of jqlite with angular. I want to use angular-ui-calendar but it depends on jquery and jquery-ui loading before angular loads.
Is there anyway to achieve this with ngMeteor?
I think optional dependencies are possible with meteor and that could be a way to achieve this... thoughts?

**Comment by Urigo** [comment]
@netanelgilad , we have s solution for that in our fork here:
https://github.com/Urigo/ngMeteor/tree/v0.2
Feel free to use, we have a full dev team that supports that fork

**Comment by netanelgilad** [comment]
@Urigo Great! thanks.. gonna use that.

**Comment by Urigo** [comment]
@netanelgilad We've just merged that change into master and released a new version to Meteor's new packaging system:
https://github.com/Urigo/ngmeteor/releases
