### ISSUE TITLE
Declaring 2 collections inserts the data to the 2nd collection

### ISSUE THREAD

**Issue by daxreyes** [loneleeandroo/ngMeteor#4]
If I modify the leaderboard example in #1 and add another Collection Member. Doing an insert via  $scope.Leaders.add({name: "leader 2"}) or lead.add({name: "leader 2"})  inserts it to Members Collection instead of Leaders Collection

Leaders = new Meteor.Collection("Leaders");
Members = new Meteor.Collection("Members");

if (Meteor.isClient) {
  ngMeteor.controller('leaderboardCtrl', ['$scope', '$collection', function($scope, $collection) {
      lead = $collection("Leaders", $scope, {}, {sort: {score: -1}});
      mem = $collection("Members", $scope, {}, {sort: {score: -1}});
      //lead.add({name:"some leader"});
      $scope.Leaders.add({name:"leader 2"});
      $scope.add = function(input){
        var leader = angular.copy(input);
        $scope.Leaders.add(leader);
        $scope.input = null;
      }
      $scope.update = function(input){
        var leader = angular.copy(input);
        angular.forEach(leader.update, function(v,k){
          if(v) leader[k] = v
        })
        $scope.Leaders.add(leader);
      }
      $scope.delete = function(input){
        $scope.Leaders.delete(input);
      }
    }
  ]);
  ngMeteor.animation('.repeat',  function() {
    return { 
      enter : function(element, done) {
        console.log("enter"); 
        done();
      },
      leave : function(element, done) {
        console.log("leave");
        done();
      },
      move: function(element, done) {
        console.log("move");
        done();
      }
    };
  });
}

**Comment by loneleeandroo** [comment]
Yep I see the problem :) Going to try to fix it soon. I might need to create a separate service for each collection.

**Comment by loneleeandroo** [comment]
I have a temporary fix for the issue :) Check out [ngMeteor v0.1.10](https://github.com/loneleeandroo/ngMeteor/releases/tag/v0.1.10)

I've tested it with the code you used above and it is inserting and deleting from the correct collection now, but the way it appears in the object is not very elegant, so I will see how i can improve it for ngMeteor v0.2.0
