### ISSUE TITLE
How to handle subscriptions

### ISSUE THREAD

**Issue by ghost** [loneleeandroo/ngMeteor#5]
I had a workaround for some days. And today i stuck over subscriptions. How can I handle subscriptions as waitOn function of Iron Router. And is there a way to do something like pagination, sorting, limiting ??

I tried to implement 
https://github.com/julianmontagna/filter-collections 

but it doesnt seem to work well together.

**Comment by ghost** [comment]
I think i get a solution from 

this - https://github.com/loneleeandroo/ngMeteor/issues/6
this - https://github.com/loneleeandroo/ngMeteor/issues/9
and this issues - https://github.com/loneleeandroo/ngMeteor/issues/11

so I am closing it. Thank u )

**Comment by daxreyes** [comment]
Wow. I had an impression it is better to use angular-ui-router when dealing with angular routing stuff. Would be nice to see a sample code  how you are able to mix and match iron-router and angular stuff
