### ISSUE TITLE
demo question: filtering

### ISSUE THREAD

**Issue by tlaskowsky** [loneleeandroo/ngMeteor#6]
Hi,

I was trying out your demo and have a question.
When I enter a single character into "search/add todo here" box, the list seems not being filtered correctly.

eg. If I added "test" into the todo-list, then enter "a" in the search field, the "test" item is still displayed.

When I enter two or more characters, the list filters correctly.
Any idea why?

Thank you!

**Comment by loneleeandroo** [comment]
Hello :)

Each todo object looks like this after its been added to Mongo:

```
{text: ... , done: ... , _id: ... }
```

In the demo, I didn't specify which properties of the object the input should filter so AngularJS automatically looks at all the properties in the todo object including the _id property as well when filtering. So if there is a letter "a" in _id, the filter will return it and it will be displayed when you type "a" in the input box.

This can be fixed. If you want the input box to only search the "text" property, you would change this line:

```
<li ng-repeat="todo in todos | filter:todoText">
```

into this:

```
<li ng-repeat="todo in todos | filter:{text:todoText}">
```

More information on the AngularJS filter can be found [here](http://docs.angularjs.org/api/ng/filter/filter)

**Comment by tlaskowsky** [comment]
Thank you very much!
