### ISSUE TITLE
How to handle browser back button

### ISSUE THREAD

**Issue by tlaskowsky** [loneleeandroo/ngMeteor#7]
Hi,

I am using ngMeteor with Iron_Router.

When I move away from an ngMeteor-enabled template and then click on the browser's back button, the data does not bind back to angular parameters.  When I refresh, they all bind and show up.

I would appreciate your advice on a work-around for this.

Thank you.

**Comment by loneleeandroo** [comment]
Yea i'm actually looking at this as well :( basically when iron-router re-renders the template, the initial render works, the DOM elements are recreated without going through the Angular $compile service. I need to add something that re-compiles the html with Angular bindings whenever a template renders.

I'm going away on a short trip soon, so this might not be done as soon as i like. I'll update the README to disclose this issue.

I guess my only workaround for now is to use the built-in [$routerProvider](http://docs.angularjs.org/api/ngRoute) or to use the [angular-ui-router](https://github.com/ccll/meteor-angular-ui-router) package.

**Comment by tlaskowsky** [comment]
Thank you Androo :)
I really appreciate your work.
This package is really helping me out on my project :)

2014-02-24 15:35 GMT-10:00 Androo notifications@github.com:

> Yea i'm actually looking at this as well :( basically when iron-router
> re-renders the template, the initial render works, the DOM elements are
> recreated without going through the Angular $compile service. I need to add
> something that re-compiles the html with Angular bindings whenever a
> template renders.
> 
> I'm going away on a short trip soon, so this might not be done as soon as
> i like. I'll update the README to disclose this issue.
> 
> I guess my only workaround for now is to use the built-in $routerProviderhttp://docs.angularjs.org/api/ngRouteor to use the
> angular-ui-router https://github.com/ccll/meteor-angular-ui-routerpackage.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/loneleeandroo/ngMeteor/issues/7#issuecomment-35965305
> .

## 

Terumi Laskowsky | Director | Credo Security Solutions LLC.
terumi@credosec.com | www.credosec.com

Disclaimer: This email and any files transmitted with it may contain
confidential information and intended solely for the use of the individual
or entity to whom they are addressed. If you have received this email in
error please notify the system manager. Please note that any views or
opinions presented in this email are solely those of the author and do not
necessarily represent those of the company. Finally, the recipient should
check this email and any attachments for the presence of viruses. The
company accepts no liability for any damage caused by any virus transmitted
by this email.

**Comment by loneleeandroo** [comment]
Hello :) Sorry it took so long! But its done. Just update to ngMeteor v0.1.16+.

Test it out!

**Comment by tlaskowsky** [comment]
Wow, thank ÿou Androo,
I will :)

On Monday, March 10, 2014, Androo notifications@github.com wrote:

> Hello :) Sorry it took so long! But its done. Just update to ngMeteor
> v0.1.16+.
> 
> Test it out!
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/loneleeandroo/ngMeteor/issues/7#issuecomment-37173642
> .

## 

Terumi Laskowsky | Director | Credo Security Solutions LLC.
terumi@credosec.com | www.credosec.com

Disclaimer: This email and any files transmitted with it may contain
confidential information and intended solely for the use of the individual
or entity to whom they are addressed. If you have received this email in
error please notify the system manager. Please note that any views or
opinions presented in this email are solely those of the author and do not
necessarily represent those of the company. Finally, the recipient should
check this email and any attachments for the presence of viruses. The
company accepts no liability for any damage caused by any virus transmitted
by this email.
