### ISSUE TITLE
How to call templates from the $routeProvider

### ISSUE THREAD

**Issue by tehXor** [loneleeandroo/ngMeteor#8]
Hi, I just started with Meteor + AngularJS and want to built a little app which should use ngRoute.

I have set  up several templates and an AngularJS app which gets loaded by ngMeteor.requires.push
Everything looks fine and I can call each template via &lt;ANY ng-template="foo"&gt;&lt;/ANY&gt;.

I have also set up a ng-view area and routes within the config block of my app with $routeProvider, These routes are working when I use them like this:
$routeProvider.when('/page1', {template: 'This is the plain text of page 1', controller: 'Page1Ctrl'});

However something like 
$routeProvider.when('/page1', {templateUrl: 'page1.html', controller: 'Page1Ctrl'});
does not work. I guess this is because such html files get transformed in template files by meteor and are not really accessible (but I could be totally wrong). 

Now you are writing in your documentation
"To invoke the template in AngularJS you could use ng-view and specify the template in the $templateCache when defining your routes using the $routeProvider..."
So I tried to load the $templateCache in the $routeProvider to achieve something like this:
$routeProvider.when('/page1', {template: $templateCache.get('page1'), controller: 'Page1Ctrl'});

But this does not work and seems futile because when you read on http://docs.angularjs.org/guide/module about the config block it says "Only providers and constants can be injected into configuration blocks. This is to prevent accidental instantiation of services before they have been fully configured."
And as $templateCache is a service I guess there is no way accessing it in the in config block.

So how is is your documentation meant and how can I achieve routing with $routeProvider? Should I define the routes somewhere else and not in the config block?

Thanks for any help and sorry if this is a noob like question...

**Comment by loneleeandroo** [comment]
Hello :)

Something like this should work:

### example.html

```
<head>
  <title>route</title>
</head>

<body>
  <div ng-view></div>
</body>

<template name="hello">
  <h1>Hello World!</h1>
  <a href="/page1">Go to Page 1</a>
</template>

<template name="page1">
  <h1>Bye World!</h1>
  <a href="/">Go back</a>
</template>
```

### example.js

```
if (Meteor.isClient) {
  ngMeteor.config(['$routeProvider', '$locationProvider',
    function($routeProvider, $locationProvider) {
      $routeProvider
      .when('/',{
        templateUrl: 'hello',
        controller: 'helloCtrl'
      })
      .when('/page1',{
        templateUrl: 'page1',
        controller: 'page1Ctrl'
      });

      $locationProvider.html5Mode(true);
    }
  ])
  .controller('helloCtrl', ['$scope', function($scope){
    console.log("hello");
  }])
  .controller('page1Ctrl', ['$scope', function($scope){
    console.log("page1");
  }]);
}
```

**Comment by loneleeandroo** [comment]
I've included an example in the README :)

**Comment by tehXor** [comment]
... I really thought I tried all possible combinations in templateUrl, however simply using the template name but the file name didn't cross my mind :(
So sorry for stealing your time but thanks a lot for answering (of course now it works as it should!) :+1: :)
